### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by davecastlevania** [DanialStoica/prj-rev-bwfs-tea-cozy#1]
https://github.com/DanialStoica/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/index.html#L5

Please go back and review the lesson about Relative Linking in Week 1 - Day 2 - HTML Tags. There is a lesson about Relative Linking for lesson 12/15 of this day that covered this a bit that can apply to web pages.

For more info about relative linking [click here](http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/)

So you should change this to 

`<link href="./stylesheet.css" type="text/css" rel="stylesheet">`

So that when other developers use your code they'll be able to see your stylings. Otherwise, other collaborators/developers won't have access to your `C:/` drive

**Comment by DanialStoica** [comment]
Thanks for the feedback! That is the same link that I provided on all my other assignments but for some reason, my css didnt work this time with this same exact format so what I did was try my C and thats what made it work. Any ideas on why My HTML couldnt fully link with my CSS with that default link?
