### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by davecastlevania** [DanialStoica/prj-rev-bwfs-tea-cozy#3]
https://github.com/DanialStoica/prj-rev-bwfs-tea-cozy/blob/master/Tea%20Cozy/stylesheet.css#L9

To center images add a class

```
.main { 
   width: 1080px;
   margin: 0 auto;
}
```

Then background images will fit in that width and auto center using margins

**Comment by DanialStoica** [comment]
Got it. Thank you
