### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by davecastlevania** [DanialStoica/prj-rev-bwfs-tea-cozy#5]
Hey there, great job on this project so far. I can tell that you've worked hard on it. I can see that there are areas of improvement that you can make understanding relative linking. This is very important to learn and you should have this concept down by the time you are done with week 1 of this course. Please ensure you have this down by the time you get to the capstone otherwise I see you having a difficult time with collaborating with other developers. So far great job, just a few improvements you will have to make to make it look to spec.

Grade: Needs Improvements

**Comment by DanialStoica** [comment]
Thank you for the feedback.
